variables:
  - &test_image 'docker.osgeo.org/postgis/build-test:trisquel3'
  - &when_path
        # related config files
        - ".woodpecker/docs.yml"
        # Makefiles
        - "doc/Makefile.in"
        # XML sources
        - "doc/*.xml"
        # Localized Makefiles
        - "doc/po/Makefile.local"
        - "doc/po/*/Makefile.local"

pipeline:
  prepare:
    image: *test_image
    pull: true
    commands:
      - ./autogen.sh
      - mkdir -p build-docs && cd build-docs
      - ../configure --without-pg
      - make postgis_revision.h
    when:
      path: *when_path
  check-xml-ja:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/ja local-check
    when:
      path:
        include:
          # related config files
          - ".woodpecker/docs.yml"
          # Makefiles
          - "doc/Makefile.in"
          # XML sources
          - "doc/*.xml"
          # Localized Makefiles
          - "doc/po/Makefile.local"
          - "doc/po/*/Makefile.local"
          - "doc/po/ja/*.po"
