variables:
  - &test_image 'docker.osgeo.org/postgis/build-test:trisquel3'
  - common_doc_paths: &common_doc_paths
      # related config files
      - ".woodpecker/docs.yml"
      # Makefiles
      - "doc/Makefile.in"
      - "doc/html/images/Makefile.in"
      # XML sources
      - "doc/*.xml"
      # Internationalization Makefiles
      - "doc/po/Makefile.local"
  - &when_path
      include:
        - <<: *common_doc_paths
  - &when_path_full
      include:
        - <<: *common_doc_paths
        # Any localized assets
        - "doc/po/*/Makefile.in"
        - "doc/po/*/*.po"

steps:
  prepare:
    image: *test_image
    pull: true
    commands:
      - ./autogen.sh
      - mkdir -p build-docs && cd build-docs
      - ../configure --without-pg --without-protobuf --without-raster
      - make postgis_revision.h
      - xmllint --version
    when:
      path: *when_path_full
  check-xml:
    image: *test_image
    pull: true
    depends_on: prepare
    commands:
      - make -C build-docs/doc check
    when:
      path: *when_path
  build-images:
    image: *test_image
    pull: true
    depends_on: check-xml
    commands:
      - make -C build-docs/doc images
    when:
      path: *when_path_full
  build-html:
    image: *test_image
    pull: true
    depends_on: prepare
    commands:
      - make -C build-docs/doc html
    when:
      path: *when_path
  build-cheatsheets:
    image: *test_image
    pull: true
    depends_on: prepare
    commands:
      - make -C build-docs/doc/ cheatsheets
    when:
      path: *when_path_full
  build-chunked-html:
    image: *test_image
    pull: true
    depends_on: prepare
    commands:
      - make -C build-docs/doc html
    when:
      path: *when_path
  build-pdf:
    image: *test_image
    pull: true
    depends_on: prepare
    commands:
      - make -C build-docs/doc/ pdf
    when:
      path: *when_path

  # DO NOT EDIT PAST THIS LINE, use update-docs-localized.sh to update #
### TARGET check-xml
  check-xml-it_IT:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/it_IT local-check-xml
    #group: localized-check-xml
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/it_IT/*.po"
  check-xml-pt_BR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pt_BR local-check-xml
    #group: localized-check-xml
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/pt_BR/*.po"
  check-xml-fr:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/fr local-check-xml
    #group: localized-check-xml
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/fr/*.po"
  check-xml-es:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/es local-check-xml
    #group: localized-check-xml
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/es/*.po"
  check-xml-pl:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pl local-check-xml
    #group: localized-check-xml
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/pl/*.po"
  check-xml-ko_KR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ko_KR local-check-xml
    #group: localized-check-xml
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ko_KR/*.po"
  check-xml-de:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/de local-check-xml
    #group: localized-check-xml
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/de/*.po"
  check-xml-ja:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ja local-check-xml
    #group: localized-check-xml
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ja/*.po"
  check-xml-ru:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ru local-check-xml
    #group: localized-check-xml
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ru/*.po"
  check-xml-zh_Hans:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/zh_Hans local-check-xml
    #group: localized-check-xml
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/zh_Hans/*.po"
  check-xml-ro:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ro local-check-xml
    #group: localized-check-xml
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ro/*.po"
  check-xml-uk:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/uk local-check-xml
    #group: localized-check-xml
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/uk/*.po"
### TARGET html
  html-it_IT:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/it_IT local-html
    #group: localized-html
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/it_IT/*.po"
  html-pt_BR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pt_BR local-html
    #group: localized-html
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/pt_BR/*.po"
  html-fr:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/fr local-html
    #group: localized-html
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/fr/*.po"
  html-es:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/es local-html
    #group: localized-html
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/es/*.po"
  html-pl:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pl local-html
    #group: localized-html
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/pl/*.po"
  html-ko_KR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ko_KR local-html
    #group: localized-html
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ko_KR/*.po"
  html-de:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/de local-html
    #group: localized-html
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/de/*.po"
  html-ja:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ja local-html
    #group: localized-html
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ja/*.po"
  html-ru:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ru local-html
    #group: localized-html
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ru/*.po"
  html-zh_Hans:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/zh_Hans local-html
    #group: localized-html
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/zh_Hans/*.po"
  html-ro:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ro local-html
    #group: localized-html
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ro/*.po"
  html-uk:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/uk local-html
    #group: localized-html
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/uk/*.po"
### TARGET cheatsheets
  cheatsheets-it_IT:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/it_IT local-cheatsheets
    #group: localized-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/it_IT/*.po"
  cheatsheets-pt_BR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pt_BR local-cheatsheets
    #group: localized-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/pt_BR/*.po"
  cheatsheets-fr:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/fr local-cheatsheets
    #group: localized-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/fr/*.po"
  cheatsheets-es:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/es local-cheatsheets
    #group: localized-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/es/*.po"
  cheatsheets-pl:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pl local-cheatsheets
    #group: localized-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/pl/*.po"
  cheatsheets-ko_KR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ko_KR local-cheatsheets
    #group: localized-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ko_KR/*.po"
  cheatsheets-de:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/de local-cheatsheets
    #group: localized-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/de/*.po"
  cheatsheets-ja:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ja local-cheatsheets
    #group: localized-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ja/*.po"
  cheatsheets-ru:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ru local-cheatsheets
    #group: localized-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ru/*.po"
  cheatsheets-zh_Hans:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/zh_Hans local-cheatsheets
    #group: localized-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/zh_Hans/*.po"
  cheatsheets-ro:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ro local-cheatsheets
    #group: localized-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ro/*.po"
  cheatsheets-uk:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/uk local-cheatsheets
    #group: localized-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/uk/*.po"
### TARGET check-cheatsheets
  check-cheatsheets-it_IT:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/it_IT local-check-cheatsheets
    #group: localized-check-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/it_IT/*.po"
  check-cheatsheets-pt_BR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pt_BR local-check-cheatsheets
    #group: localized-check-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/pt_BR/*.po"
  check-cheatsheets-fr:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/fr local-check-cheatsheets
    #group: localized-check-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/fr/*.po"
  check-cheatsheets-es:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/es local-check-cheatsheets
    #group: localized-check-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/es/*.po"
  check-cheatsheets-pl:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pl local-check-cheatsheets
    #group: localized-check-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/pl/*.po"
  check-cheatsheets-ko_KR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ko_KR local-check-cheatsheets
    #group: localized-check-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ko_KR/*.po"
  check-cheatsheets-de:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/de local-check-cheatsheets
    #group: localized-check-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/de/*.po"
  check-cheatsheets-ja:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ja local-check-cheatsheets
    #group: localized-check-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ja/*.po"
  check-cheatsheets-ru:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ru local-check-cheatsheets
    #group: localized-check-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ru/*.po"
  check-cheatsheets-zh_Hans:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/zh_Hans local-check-cheatsheets
    #group: localized-check-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/zh_Hans/*.po"
  check-cheatsheets-ro:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ro local-check-cheatsheets
    #group: localized-check-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ro/*.po"
  check-cheatsheets-uk:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/uk local-check-cheatsheets
    #group: localized-check-cheatsheets
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/uk/*.po"
### TARGET pdf
  pdf-it_IT:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/it_IT local-pdf
    #group: localized-pdf
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/it_IT/*.po"
  pdf-pt_BR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pt_BR local-pdf
    #group: localized-pdf
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/pt_BR/*.po"
  pdf-fr:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/fr local-pdf
    #group: localized-pdf
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/fr/*.po"
  pdf-es:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/es local-pdf
    #group: localized-pdf
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/es/*.po"
  pdf-pl:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/pl local-pdf
    #group: localized-pdf
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/pl/*.po"
  pdf-ko_KR:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ko_KR local-pdf
    #group: localized-pdf
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ko_KR/*.po"
  pdf-de:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/de local-pdf
    #group: localized-pdf
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/de/*.po"
  pdf-ja:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ja local-pdf
    #group: localized-pdf
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ja/*.po"
  pdf-ru:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ru local-pdf
    #group: localized-pdf
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ru/*.po"
  pdf-zh_Hans:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/zh_Hans local-pdf
    #group: localized-pdf
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/zh_Hans/*.po"
  pdf-ro:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/ro local-pdf
    #group: localized-pdf
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/ro/*.po"
  pdf-uk:
    image: *test_image
    pull: true
    commands:
      - make -C build-docs/doc/po/uk local-pdf
    #group: localized-pdf
    #depends_on: prepare
    when:
      path:
        include:
          - "doc/po/uk/*.po"
