variables:
  test-image: &test-image docker.osgeo.org/postgis/build-test:trisquel3

clone:
  clone:
    image: woodpeckerci/plugin-git
    depth: 50

steps:

  autogen:
    image: *test-image
    pull: true
    commands:
      - ./autogen.sh

  regress-pg12:
    image: *test-image
    group: build
    environment:
      - PGVER=12
      - POSTGIS_REGRESS_DB_OWNER=postgis_reg_unprivileged_user
      - RUNTESTFLAGS=--after-create-db-script $${CI_WORKSPACE}/regress/hooks/configure-pgextwlist.sql
    commands:
      - sh ci/dronie/postgis_regress.sh

  regress-pg15:
    image: *test-image
    group: build
    environment:
      - PGVER=15
      - POSTGIS_REGRESS_DB_OWNER=postgis_reg_unprivileged_user
      - RUNTESTFLAGS=--after-create-db-script $${CI_WORKSPACE}/regress/hooks/configure-pgextwlist.sql
    commands:
      - sh ci/dronie/postgis_regress.sh
